# FOSJsRoutingBundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
   
_logout:
    path: /logout

# Home Bundle
home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

# Contract Bundle
contract:
    resource: "@ContractBundle/Resources/config/routing.yml"
    prefix:   /

# Core Bundle
core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

# Aircraft Bundle
aircraft:
    resource: "@AircraftBundle/Resources/config/routing.yml"
    prefix:   /

# Oil Industry Bundle
oil_industry:
    resource: "@OilIndustryBundle/Resources/config/routing.yml"
    prefix:   /

# Admin Bundle
admin_tools:
    resource: "@AdminToolsBundle/Resources/config/routing.yml"
    prefix:   /

# Database Bundle
database:
    resource: "@DatabaseBundle/Resources/config/routing.yml"
    prefix:   /
    