# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ~
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:                    ^/
            form_login:
                provider:               fos_userbundle
                csrf_token_generator:   security.csrf.token_manager
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
                default_target_path:    /home
            logout:
                path:                   fos_user_security_logout
                target:                 /login
            remember_me:
                key:                    %secret%
            logout:                     true
            anonymous:                  true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/change-password, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/home, role: ROLE_USER }
        - { path: ^/contracts, role: ROLE_USER }
        - { path: ^/aircraft, role: ROLE_USER }
        - { path: ^/oilIndustry, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/_console, role: IS_SUPER_ADMIN }
