<?php

namespace Proxies\__CG__\DatabaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HelicopterClass extends \DatabaseBundle\Entity\HelicopterClass implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'id', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'helicopterClassName', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'helicopterFleet', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'operatorsHelicopters', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'helicopterCategory', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'constructor'];
        }

        return ['__isInitialized__', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'id', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'helicopterClassName', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'helicopterFleet', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'operatorsHelicopters', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'helicopterCategory', '' . "\0" . 'DatabaseBundle\\Entity\\HelicopterClass' . "\0" . 'constructor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HelicopterClass $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHelicopterClassName($helicopterClassName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHelicopterClassName', [$helicopterClassName]);

        return parent::setHelicopterClassName($helicopterClassName);
    }

    /**
     * {@inheritDoc}
     */
    public function getHelicopterClassName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHelicopterClassName', []);

        return parent::getHelicopterClassName();
    }

    /**
     * {@inheritDoc}
     */
    public function addHelicopterFleet(\DatabaseBundle\Entity\HelicopterFleet $helicopterFleet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHelicopterFleet', [$helicopterFleet]);

        return parent::addHelicopterFleet($helicopterFleet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHelicopterFleet(\DatabaseBundle\Entity\HelicopterFleet $helicopterFleet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHelicopterFleet', [$helicopterFleet]);

        return parent::removeHelicopterFleet($helicopterFleet);
    }

    /**
     * {@inheritDoc}
     */
    public function getHelicopterFleet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHelicopterFleet', []);

        return parent::getHelicopterFleet();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperatorsHelicopter(\DatabaseBundle\Entity\OperatorsHelicopters $operatorsHelicopters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperatorsHelicopter', [$operatorsHelicopters]);

        return parent::addOperatorsHelicopter($operatorsHelicopters);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperatorsHelicopter(\DatabaseBundle\Entity\OperatorsHelicopters $operatorsHelicopters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperatorsHelicopter', [$operatorsHelicopters]);

        return parent::removeOperatorsHelicopter($operatorsHelicopters);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperatorsHelicopters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperatorsHelicopters', []);

        return parent::getOperatorsHelicopters();
    }

    /**
     * {@inheritDoc}
     */
    public function setHelicopterCategory(\DatabaseBundle\Entity\HelicopterCategory $helicopterCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHelicopterCategory', [$helicopterCategory]);

        return parent::setHelicopterCategory($helicopterCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getHelicopterCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHelicopterCategory', []);

        return parent::getHelicopterCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructor(\DatabaseBundle\Entity\Constructor $constructor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructor', [$constructor]);

        return parent::setConstructor($constructor);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructor', []);

        return parent::getConstructor();
    }

}
