<?php

namespace Proxies\__CG__\DatabaseBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Helicopter extends \DatabaseBundle\Entity\Helicopter implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'id', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'serialNumber', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'register', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'helicopterComments', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'helicopterClass', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'owner', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'helicopterStatus', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'operatorGroup', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'base'];
        }

        return ['__isInitialized__', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'id', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'serialNumber', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'register', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'helicopterComments', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'helicopterClass', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'owner', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'helicopterStatus', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'operatorGroup', '' . "\0" . 'DatabaseBundle\\Entity\\Helicopter' . "\0" . 'base'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Helicopter $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerialNumber($serialNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerialNumber', [$serialNumber]);

        return parent::setSerialNumber($serialNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerialNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerialNumber', []);

        return parent::getSerialNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegister($register)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegister', [$register]);

        return parent::setRegister($register);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegister', []);

        return parent::getRegister();
    }

    /**
     * {@inheritDoc}
     */
    public function addHelicopterComment(\DatabaseBundle\Entity\HelicopterComment $helicopterComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHelicopterComment', [$helicopterComments]);

        return parent::addHelicopterComment($helicopterComments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHelicopterComment(\DatabaseBundle\Entity\HelicopterComment $helicopterComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHelicopterComment', [$helicopterComments]);

        return parent::removeHelicopterComment($helicopterComments);
    }

    /**
     * {@inheritDoc}
     */
    public function getHelicopterComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHelicopterComments', []);

        return parent::getHelicopterComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setHelicopterClass(\DatabaseBundle\Entity\HelicopterClass $helicopterClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHelicopterClass', [$helicopterClass]);

        return parent::setHelicopterClass($helicopterClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getHelicopterClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHelicopterClass', []);

        return parent::getHelicopterClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\DatabaseBundle\Entity\Owner $owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setHelicopterStatus(\DatabaseBundle\Entity\HelicopterStatus $helicopterStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHelicopterStatus', [$helicopterStatus]);

        return parent::setHelicopterStatus($helicopterStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getHelicopterStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHelicopterStatus', []);

        return parent::getHelicopterStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperatorGroup(\DatabaseBundle\Entity\Helicopter $operatorGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperatorGroup', [$operatorGroup]);

        return parent::setOperatorGroup($operatorGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperatorGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperatorGroup', []);

        return parent::getOperatorGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setBase(\DatabaseBundle\Entity\Base $base = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBase', [$base]);

        return parent::setBase($base);
    }

    /**
     * {@inheritDoc}
     */
    public function getBase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBase', []);

        return parent::getBase();
    }

}
