<?php

namespace DatabaseBundle\Repository;

/**
 * AlternateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlternateRepository extends \Doctrine\ORM\EntityRepository
{
}
