<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
    public function singleObjectBuilder($base){
        
        $myBase = array();
        $gps = array();
        
        if (!empty($base) && $base !== null){
            
            $gps['lat'] = $base->getLatitude();
            $gps['lng'] = $base->getLongitude();
            
            if($base->getOperatorGroup() != null){
                $operator = $base->getOperatorGroup()->getOperatorGroupName();
            }
            else{
                $operator = "None";
            }
            
            $myBase['id'] = $base->getId();
            $myBase['name'] = $base->getBaseName();
            $myBase['country'] = $base->getCountry()->getCountryName();
            $myBase['airportLink'] = $base->getAirportLink();
            $myBase['operatorGroup'] = $operator;
            
            $myBase['gps'] = $gps;
        }
        else{
            throw new \ErrorException("Variable \$base is empty or null.");
        }
        
        return $myBase;
        
    }
}
