<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessAreaRepository extends EntityRepository
{
    public function singleObjectBuilder($businessArea){
        
        $myBusinessArea = array();
        $gps = array();
        
        if (!empty($businessArea) && $businessArea !== null){
            
            $myBusinessArea['id'] = $businessArea->getId();
            $myBusinessArea['name'] = $businessArea->getBusinessAreaName();

        }
        else{
            throw new \ErrorException("Variable \$businessArea is empty or null.");
        }
        
        return $myBusinessArea;
        
    }
}
