<?php

namespace DatabaseBundle\Repository;

/**
 * CountryAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
