<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function singleObjectBuilder($country){
        
        $myCountry = array();
        
        if(!empty($country) && $country !== null){
            
            $myCountry['id'] = $country->getId();
            $myCountry['name'] = $country->getCountryName();
            $myCountry['countryCode'] = $country->getCountryCode();
            $myCountry['countryFullName'] = $country->getCountryFullName();
            $myCountry['organisationLink'] = $country->getOrganisationlink();
            if ( ($geographicalArea = $country->getGeographicalArea()) !== null ){
                $myCountry['geographicalArea'] = $geographicalArea->getGeographicalAreaName();
            }          
            
        }
        else{
            throw new \ErrorException('Variable \$country is empty or null.');
        }
        
        return $myCountry;
    }
    
}
