<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GeographicalAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeographicalAreaRepository extends EntityRepository
{
    public function singleObjectBuilder($geographicalArea){
        
        $myGeographicalArea = array();
        
        if(!empty($geographicalArea) && $geographicalArea !== null){
            
            $myGeographicalArea['id'] = $geographicalArea->getId();
            $myGeographicalArea['name'] = $geographicalArea->getGeographicalAreaName();
            
        }
        else{
            throw new \ErrorException('Variable \$geographicalArea is empty or null.');
        }
        
        return $myGeographicalArea;
        
    }
}
