<?php

namespace DatabaseBundle\Repository;

/**
 * GlobalOperatorGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalOperatorGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
