<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HelicopterCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelicopterCategoryRepository extends EntityRepository
{
    public function singleObjectBuilder($helicopterCategory){
        
        $myHelicopterCategory = array();
        
        if(!empty($helicopterCategory) && $helicopterCategory !== null){
            
            $myHelicopterCategory['id'] = $helicopterCategory->getId();
            $myHelicopterCategory['name'] = $helicopterCategory->getHelicopterCategoryName();
            
        }
        else{
            throw new \ErrorException('Variable \$country is empty or null.');
        }
        
        return $myHelicopterCategory;
        
    }
}
