<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HelicopterClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelicopterClassRepository extends EntityRepository
{
    public function singleObjectBuilder($helicopterClass){
        
        $myHelicopterClass = array();
        
        if(is_a($helicopterClass, 'DatabaseBundle\Entity\HelicopterClass') && $helicopterClass !== null){
            $myHelicopterClass['id'] = $helicopterClass->getId();
            $myHelicopterClass['name'] = $helicopterClass->getHelicopterClassName();
        }
        else{
            throw new \ErrorException('Variable \$helicopterClass type error ! Expected type : DatabaseBundle\Entity\HelicopterClass object.');
        }
        
        return $myHelicopterClass;
        
    }
}
