<?php

namespace DatabaseBundle\Repository;

/**
 * MissionToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionToolRepository extends \Doctrine\ORM\EntityRepository
{
}
