<?php

namespace DatabaseBundle\Repository;

/**
 * MissionAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
