<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OilCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OilCompanyRepository extends EntityRepository
{
    public function singleObjectBuilder($oilCompany){
        
        $myOilCompany = array();
        
        if (!empty($oilCompany) && $oilCompany !== null){
            
            $myOilCompany['id'] = $oilCompany->getId();
            $myOilCompany['name'] = $oilCompany->getOilCompanyName();
            $myOilCompany['introduction'] = $oilCompany->getShortIntroduction();
            $myOilCompany['websiteLink'] = $oilCompany->getWebSiteLink();
            $myOilCompany['investorsLink'] = $oilCompany->getInvestorsLink();
            
        }
        else{
            throw new \ErrorException("Variable \$oilCompany is empty or null.");
        }
        
        return $myOilCompany;
        
    }
}
