<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OperatorGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorGroupRepository extends EntityRepository
{
    public function singleObjectBuilder($operatorGroup){
        
        $myOperatorGroup = array();
        
        if (!empty($operatorGroup) && $operatorGroup !== null){
            
            $myOperatorGroup['id'] = $operatorGroup->getId();
            $myOperatorGroup['name'] = $operatorGroup->getOperatorGroupName();
            
            if ($operatorGroup->getGlobalOperatorGroup() !== null){
                $myOperatorGroup['globalOperatorGroup'] = $operatorGroup->getGlobalOperatorGroup()->getGlobalOperatorGroupName();
            }
            else{
                $myOperatorGroup['globalOperatorGroup'] = "Unknown";
            }
            
        }
        else{
            throw new \ErrorException("Variable \$operatorGroup is empty or null.");
        }
        
        return $myOperatorGroup;
    }
}
