<?php

namespace DatabaseBundle\Repository;

/**
 * PlatformStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function singleObjectBuilder($platformStatus){
        
        $myPlatformStatus = array();
        
        if (!empty($platformStatus) && $platformStatus !== null){
            
            $myPlatformStatus['id'] = $platformStatus->getId();
            $myPlatformStatus['name'] = $platformStatus->getPlatformStatusName();

        }
        else{
            throw new \ErrorException("Variable \$platform is empty or null.");
        }
        
        return $myPlatformStatus;
        
    }
}
