<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformRepository extends EntityRepository
{
    
    public function singleObjectBuilder($platform){
        
        $myPlatform = array();
        
        if (!empty($platform) && $platform !== null){
            
            $myPlatform['id'] = $platform->getId();
            $myPlatform['name'] = $platform->getPlatformName();
            $myPlatform['area'] = $platform->getCountry()->getGeographicalArea()->getGeographicalAreaName();
            $myPlatform['country'] = $platform->getCountry()->getCountryName();
            $myPlatform['platformStatus'] = $platform->getPlatformStatus()->getPlatformStatusName();
            
            if($platform->getField() != null){
                $myPlatform['fieldName'] = $platform->getField()->getFieldName();
            }
            if ($platform->getBlock() != null){
                $myPlatform['block'] = $platform->getBlock()->getBlockNumber();
            }
            
            $startYear = $platform->getPlatformDate()->format('Y');
            $myPlatform['startYear'] = $startYear;
            
            $removalYear = $platform->getPlatformRemovalDate();
            
            if ($removalYear == null){
                $myPlatform['removalYear'] = "Unknown";
            }
            else{
                $removalYear = $removalYear->format('Y');
                $myPlatform['removalYear'] = $removalYear;
            }     
            
            $myPlatform['bunkedBedNumber'] = $platform->getBunkedBedNumber();
            $myPlatform['oilCompany'] = $platform->getOilCompany()->getOilCompanyName();
            
            if($platform->getBase() !== null){
                $myPlatform['base'] = $platform->getBase()->getBaseName();
            }
            
            $myPlatform['distance'] = $platform->getNearestBaseDistance();
            $myPlatform['coastDistance'] = $platform->getCoastDistance();
            $myPlatform['dValue'] = $platform->getHelideckDValue();
            $myPlatform['tValue'] = $platform->getHelideckTValue();
            
            if ($platform->getRefuellingOption()){
                $myPlatform['refuellingOption'] = "Available";
            }
            else{
                $myPlatform['refuellingOption'] = "Unavailable";
            }
            
            $myPlatform['gps'] = array( 'lat' => $platform->getLatitude(),
                                        'lng' => $platform->getLongitude());
        }
        else{
            throw new \ErrorException("Variable \$platform is empty or null.");
        }
        
        return $myPlatform;
        
    }
}
