<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectPlatformCircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPlatformCircuitRepository extends EntityRepository
{
}
