<?php

namespace DatabaseBundle\Repository;

/**
 * ProjectAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectAreaRepository extends \Doctrine\ORM\EntityRepository
{
    public function singleObjectBuilder($projectArea){
        
        $myProjectArea = array();
        
        if(!empty($projectArea) && $projectArea !== null){
            $myProjectArea['id'] = $projectArea->getId();
            $myProjectArea['gps'] = array('lat' => $projectArea->getProjectAreaLatitude(),
                                          'lng' => $projectArea->getProjectAreaLongitude());
        }
        else{
            throw new \ErrorException('Variable \$projectArea is empty or null.');
        }
 
        return $myProjectArea;
        
    }
}
