<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStatusRepository extends EntityRepository
{
    
    public function singleObjectBuilder($projectStatus){
        
        $myProjectStatus = array();
        
        if(!empty($projectStatus) && $projectStatus !== null){
            
            $myProjectStatus['id'] = $projectStatus->getId();
            $myProjectStatus['name'] = $projectStatus->getProjectStatusName(); 
            
        }
        else{
            throw new \ErrorException('Variable \$projectStatus is empty or null.');
        }
        
        return $myProjectStatus;
    }
}
