<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function singleObjectBuilder($user){
        
        $myUser = array();
        
        if($user != null && !empty($user)){
            
            $myUser['id'] = $user->getId();
            
            if ($user->getFirstName() != null){
                $myUser['firstName'] = $user->getFirstName();
            }
            else{
                $myUser['firstName'] = "Missing user first name !";
            }
            if ($user->getLastName() != null){
                $myUser['lastName'] = $user->getLastName();
            }
            else{
                $myUser['lastName'] = "Missing user last name !";
            }
            if($user->getEmail() != null){
                $myUser['email'] = $user->getEmail();
            }
            else{
                $myUser['email'] = "Missing user email address !";
            }
            if($user->getEnabled() != null){
                $myUser['status'] = $user->getEnabled();
            }
            else{
                $myUser['status'] = "Missing user account status !";
            }
            if($user->getService() != null){
                $myUser['service'] = $user->getService->getServiceName();
            }
            else{
                $myUser['service'] = "Undefined";
            }
            if($user->getBusinessArea() != null){
                $myUser['businessArea'] = $user->getBusinessArea()->getBusinessAreaName();
            }
            else{
                $myUser['businessArea'] = null;
            }
            if($user->getLastLogin() != null){
                $lastLogin = $user->getLastLogin(); 
                $myUser['lastLogin'] = $lastLogin->format('d/m/Y');
            }
            else{
                $myUser['lastLogin'] = "";
            }
            
        }
        else{
            throw new \ErrorException('Variable \$user is empty or null.');
        }
        
        return $myUser;
        
    }
    
}
